shell:
  extends:
    service: base
  volumes:
    - .:/py-pdf-parser
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ./imagemagick_policy.xml:/etc/ImageMagick-6/policy.xml
  environment:
    - DISPLAY
  command: bash

lint:
  extends:
    service: base
  command: ./.github/scripts/lint.sh

lint-fix:
  extends:
    service: base
  command: bash -c "black . && isort ."

tests:
  extends:
    service: base
  command: .github/scripts/test.sh

# Run docs to re-build the docs once.
docs:
  extends:
    service: base
  command: make --directory docs html
  environment:
    - SPHINXOPTS="-W"

# Use "up" to host the docs on port 8000, watching for changes.
docs-autobuild:
  extends:
    service: base
  ports:
    - "8000:8000"
  command: make --directory docs livehtml

base:
  build: .
  volumes:
    - .:/py-pdf-parser
  working_dir: /py-pdf-parser
