shell:
  build: .
  volumes:
    - .:/py-pdf-parser
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ./imagemagick_policy.xml:/etc/ImageMagick-6/policy.xml
  environment:
    - DISPLAY
  command: bash

lint:
  build: .
  volumes:
    - .:/py-pdf-parser
  command: bash -c "black . --check && mypy . && pytype . --disable=pyi-error,import-error && pycodestyle . --config=pycodestyle.cfg"

lint-fix:
  build: .
  volumes:
    - .:/py-pdf-parser
  command: bash -c "black ."

tests:
  build: .
  volumes:
    - .:/py-pdf-parser
  command: .github/scripts/test.sh

# Run docs to re-build the docs once.
docs:
  build: .
  volumes:
    - .:/py-pdf-parser
  command: make --directory docs html
  environment:
    - SPHINXOPTS="-W"

# Use "up" to host the docs on port 8000, watching for changes.
docs-autobuild:
  build: .
  volumes:
    - .:/py-pdf-parser
  ports:
    - "8000:8000"
  command: make --directory docs livehtml
