name: Publish new version
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: actions/setup-python@master
    - name: Install build packages
      run: pip3 install twine==3.1.1 wheel==0.34.2
    - name: Build package
      run: python3 setup.py sdist bdist_wheel
    - name: Check built package
      run: twine check dist/*
    - name: Publish package to PyPI
      run: twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
