name: Publish new version
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@master
    - name: Get the tag
      id: tagName
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to docker hub
      uses: docker/build-push-action@v2.4.0
      with:
        context: .
        file: dockerfiles/Dockerfile
        tags: jstockwin/py-pdf-parser:${{ steps.tagName.outputs.tag }}
    - name: Install build packages
      run: pip3 install twine==3.1.1 wheel==0.34.2
    - name: Build package
      run: python3 setup.py sdist bdist_wheel
    - name: Check built package
      run: twine check dist/*
    - name: Publish package to PyPI
      run: twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
